package history;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import util.DataSaver;
/**
 * DailyData contains two string array lists. The first list is a log of every transaction, and the
 * second list holds a log of the garage. 
 * @author chris demonte
 *
 */

import model.*;
import util.*;
public class DailyData implements Serializable{

	private static final long serialVersionUID = -2995963835008199289L;
	/**
	 * @param salesLog is a list of strings representing transactions
	 * @param garageLog is a record of the garage at certain times of the day
	 */
	ArrayList<String> salesLog;
	ArrayList<String> garageLog;
	
	public DailyData() {
		salesLog = new ArrayList<String>();
		garageLog = new ArrayList<String>();
		this.startLogs();
	}

	/**
	 * This method is called once when initializing the DailyData class 
	 */
	private void startLogs() {
		Date date = new Date();
		String openRegister = new String ("Register Opened: " + date.toString());
		salesLog.add(openRegister);
		String openParkingLot = new String ("Parking Lot Opened " + date.toString());
		garageLog.add(openParkingLot);
	}
	/**
	 * Adds a copy of a transaction receipt to the data logs.
	 * @param transaction a string that is generated by the ticket class
	 */
	public void logTransaction (String transaction) {
		salesLog.add(transaction);
	}
	/**
	 * Logs the status of the ParkingLot and each individual spot into the data logs
	 * @param lotData
	 */
	public void logGarage(ParkingLot lotData) {
		Date date = new Date();
		garageLog.add(date.toString() + "\n" + lotData.toString());
	}

	/**
	 * Overrides the Object toString method to output the data logs in a readable format
	 */
	@Override
	public String toString() {
		Date date = new Date();
		String output = new String();
		output += "Garage Log : " + date.toString() + "\n";
		output += "****************************************\n"
				+ "\tSales\n"
				+ "****************************************\n";
		for (int i = 0; i < salesLog.size(); i++) {
			output += salesLog.get(i);
		}
		output += "\n****************************************\n"
				+ "\tGarage\n"
				+ "****************************************\n";
		for (int i = 0; i < garageLog.size(); i++) {
			output += garageLog.get(i);
			output += "\n****************************************\n";
		}
	
		return output;
	}
	/**
	 * Saves the data to a file using the month and day
	 */
	public void saveDailyData() {
		LocalDate date = LocalDate.now();
		String adr = "resources/daily" + date.getMonthValue() + date.getDayOfMonth() + ".data";
		DataSaver.writeObject(this, adr);
	}
}
