package view;

import static util.LightWork.initGridPaneSettings;

import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;
import userData.UserDataManager;

/**
 * For adding users to the Account Data Structure
 * User is auto-generated by first name and last name.  
 * @author Camposm97
 */
public class InsertUserPane extends GridPane {
	private UserDataManager users;
	private TextField tfFirstname, tfLastname, tfUsername;
	private PasswordField tfPassword;
	private Button btAdd;
	
	public InsertUserPane(UserDataManager users) {
		this.users = users;
		initGridPaneSettings(this);
		initControls();
		showControls();
	}
	
	private void initControls() {
		tfFirstname = new TextField();
		tfLastname = new TextField();
		tfUsername = new TextField();
		tfPassword = new PasswordField();
		btAdd = new Button("User");
	}
	
	private void showControls() {
		Label lblFirst = new Label("First Name:");
		Label lblLast = new Label("Last Name:");
		Label lblUsername = new Label("Username");
		Label lblPassword = new Label("Password:");
		addColumn(0, lblFirst, lblLast, lblUsername, lblPassword);
	}
}
