package view;

import static util.LightWork.DEFAULT_INSETS;

import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;

/**
 * For adding users to the Account Data Structure
 * User is auto-generated by first name and last name.  
 * @author Camposm97
 */
public class SignUpPane extends GridPane {
	private TextField tfFirstname, tfLastname, tfUsername;
	private PasswordField tfPassword;
	
	public SignUpPane() {
		initControls();
		showControls();
	}
	
	private void initControls() {
		tfFirstname = new TextField();
		tfLastname = new TextField();
		tfUsername = new TextField();
		tfPassword = new PasswordField();
	}
	
	private void showControls() {
		Label lblFirst = new Label("First Name:");
		Label lblLast = new Label("Last Name:");
		Label lblUsername = new Label("Username");
		Label lblPassword = new Label("Password:");
		
		setAlignment(Pos.CENTER);
		setPadding(DEFAULT_INSETS);
	}
}
